SET FOREIGN_KEY_CHECKS=0;



DROP TABLE IF EXISTS CITATION
;
DROP TABLE IF EXISTS CONCEPT
;
DROP TABLE IF EXISTS CONCEPT_CITATION
;
DROP TABLE IF EXISTS CONCEPT_MAPPING
;
DROP TABLE IF EXISTS CONCEPT_SEMANTIC_TYPE
;
DROP TABLE IF EXISTS CONCEPT_TERM
;
DROP TABLE IF EXISTS DESCRIPTION
;
DROP TABLE IF EXISTS EXTERNAL_ONTOLOGY
;
DROP TABLE IF EXISTS RELATIONSHIP
;
DROP TABLE IF EXISTS SEMANTIC_TYPE
;
DROP TABLE IF EXISTS SEMANTIC_TYPE_PARENT_REL
;

CREATE TABLE CITATION
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DOI VARCHAR(255),
	YEAR INTEGER,
	SOURCE TEXT,
	STR TEXT NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_CITATION_ID(ID)
) 
;


CREATE TABLE CONCEPT
(
	CUI VARCHAR(50) NOT NULL,
	STR VARCHAR(100) NOT NULL,
	IS_REL BOOL NOT NULL,
	PRIMARY KEY (CUI),
	UNIQUE UQ_CONCEPT_CUI(CUI)
) 
;


CREATE TABLE CONCEPT_CITATION
(
	CUI VARCHAR(50) NOT NULL,
	CITATION_ID INTEGER NOT NULL,
	PRIMARY KEY (CUI, CITATION_ID),
	KEY (CITATION_ID),
	KEY (CUI)
) 
;


CREATE TABLE CONCEPT_MAPPING
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CUI VARCHAR(50) NOT NULL,
	ONTOLOGY VARCHAR(50) NOT NULL,
	CONCEPT VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID),
	KEY (CUI),
	KEY (ONTOLOGY)
) 
;


CREATE TABLE CONCEPT_SEMANTIC_TYPE
(
	CUI VARCHAR(50) NOT NULL,
	TID CHAR(7) NOT NULL,
	PRIMARY KEY (CUI, TID),
	KEY (CUI),
	KEY (TID)
) 
;


CREATE TABLE CONCEPT_TERM
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CUI VARCHAR(50) NOT NULL,
	LANG VARCHAR(50) NOT NULL,
	STR VARCHAR(255) NOT NULL,
	IS_PREF BOOL NOT NULL,
	IS_ABBR BOOL NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_SYNONYM_ID(ID),
	KEY (CUI)
) 
;


CREATE TABLE DESCRIPTION
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CUI VARCHAR(50),
	LANG VARCHAR(50) NOT NULL,
	STR TEXT NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_DESCRIPTION_ID(ID),
	KEY (CUI)
) 
;


CREATE TABLE EXTERNAL_ONTOLOGY
(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PREFIX VARCHAR(255) NOT NULL,
	DOCUMENT_URL VARCHAR(255),
	DESCRIPTION TEXT,
	PRIMARY KEY (ID)
) 
;


CREATE TABLE RELATIONSHIP
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CUI1 VARCHAR(50) NOT NULL,
	CUI2 VARCHAR(50) NOT NULL,
	REL_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_RELATIONSHIP_ID(ID),
	KEY (REL_ID),
	KEY (CUI1),
	KEY (CUI2)
) 
;


CREATE TABLE SEMANTIC_TYPE
(
	TID CHAR(7) NOT NULL,
	STR VARCHAR(255),
	PRIMARY KEY (TID),
	UNIQUE UQ_SEMANTIC_TYPE_TID(TID)
) 
;


CREATE TABLE SEMANTIC_TYPE_PARENT_REL
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	TID_CHILD CHAR(7) NOT NULL,
	TID_PARENT CHAR(7) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_SEMANTIC_TYPE_PARENT_REL_ID(ID),
	KEY (TID_CHILD),
	KEY (TID_PARENT)
) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE CONCEPT_CITATION ADD CONSTRAINT FK_CONCITATION_CITATION 
	FOREIGN KEY (CITATION_ID) REFERENCES CITATION (ID)
;

ALTER TABLE CONCEPT_CITATION ADD CONSTRAINT FK_CONCITATION_CON 
	FOREIGN KEY (CUI) REFERENCES CONCEPT (CUI)
;

ALTER TABLE CONCEPT_MAPPING ADD CONSTRAINT FK_CONCEPT_MAPPING_CONCEPT 
	FOREIGN KEY (CUI) REFERENCES CONCEPT (CUI)
;

ALTER TABLE CONCEPT_MAPPING ADD CONSTRAINT FK_CONCEPT_MAPPING_EXTERNAL_ONTOLOGY 
	FOREIGN KEY (ONTOLOGY) REFERENCES EXTERNAL_ONTOLOGY (ID)
;

ALTER TABLE CONCEPT_SEMANTIC_TYPE ADD CONSTRAINT FK_CONSEMTYPE_CONCEPT 
	FOREIGN KEY (CUI) REFERENCES CONCEPT (CUI)
;

ALTER TABLE CONCEPT_SEMANTIC_TYPE ADD CONSTRAINT FK_CONSEMTYPE_SEMTYPE 
	FOREIGN KEY (TID) REFERENCES SEMANTIC_TYPE (TID)
;

ALTER TABLE CONCEPT_TERM ADD CONSTRAINT FK_SYNONYM_CONCEPT 
	FOREIGN KEY (CUI) REFERENCES CONCEPT (CUI)
;

ALTER TABLE DESCRIPTION ADD CONSTRAINT FK_DESCRIPTION_CONCEPT 
	FOREIGN KEY (CUI) REFERENCES CONCEPT (CUI)
;

ALTER TABLE RELATIONSHIP ADD CONSTRAINT FK_REL_CONCEPT 
	FOREIGN KEY (REL_ID) REFERENCES CONCEPT (CUI)
;

ALTER TABLE RELATIONSHIP ADD CONSTRAINT FK_REL_CON1 
	FOREIGN KEY (CUI1) REFERENCES CONCEPT (CUI)
;

ALTER TABLE RELATIONSHIP ADD CONSTRAINT FK_REL_CON2 
	FOREIGN KEY (CUI2) REFERENCES CONCEPT (CUI)
;

ALTER TABLE SEMANTIC_TYPE_PARENT_REL ADD CONSTRAINT FK_SEMTYPE_CHILD_REL_DEF 
	FOREIGN KEY (TID_CHILD) REFERENCES SEMANTIC_TYPE (TID)
;

ALTER TABLE SEMANTIC_TYPE_PARENT_REL ADD CONSTRAINT FK_SEMTYPE_PARENT_REL_DEF 
	FOREIGN KEY (TID_PARENT) REFERENCES SEMANTIC_TYPE (TID)
;
